title: Andre Ye
name: ğŸ“
author: ğŸ“ 
baseurl: "/"
description: A site for my notes and thoughts.
profile_url: "http://andre-ye.github.io"

minima:
  skin: dark

theme: minima #jekyll-theme-cayman
markdown: kramdown
header_pages:
  - home.md

github_username: andre-ye
linkedin_username: andre-ye
